version: "3.7"
services:
  jenkins:
    image: jenkins/jenkins:lts
    # only for dev (gives access to docer)
    user: root:root
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
  ci-cd-generator:
    image: bankiru/git-daemon
    volumes:
      - .:/git