version: "3.7"
services:
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - ./jenkins_home:/var/jenkins_home
    ports:
      - 8080:8080
  ci-cd-generator:
    image: bankiru/git-daemon
    volumes:
      - .:/git